sudo: false
dist: xenial
language: php

services:
  - mysql
  - postgresql

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # clone UserFrosting
  - cd ../
  - git clone https://github.com/userfrosting/UserFrosting.git
  - cd UserFrosting
  # move and add sprinkle
  - mv ../UF_FormGenerator app/sprinkles/FormGenerator/
  - echo "{\"base\":[\"core\",\"account\",\"admin\",\"FormGenerator\"]}" > app/sprinkles.json

before_script:
  # install deps and UF
  - composer install

script:
  # run unit tests
  - app/vendor/bin/phpunit -c app/sprinkles/FormGenerator/phpunit.xml --coverage-clover=app/sprinkles/FormGenerator/coverage.xml

after_failure:
  - cat app/log/userfrosting.log

after_success:
  - cd app/sprinkles/FormGenerator/
  - bash <(curl -s https://codecov.io/bash)
